name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"
      - name: Install Python dependencies
        run: pip install black flake8
      - name: Run Black
        run: black --check .
      - name: Run Flake8
        run: flake8 .
